### PR TITLE
Build fixes for compiling as a dynamic module

### PR DESCRIPTION
**Pull request by akatrevorjay**

### CODE REVIEW

**Comment by xiaokai-wang** [comment]
Making the two commits into one? A new pr?

Thanks.

**Comment by akatrevorjay** [comment]
@xiaokai-wang You can squash merge right from GitHub now!
image

**Comment by xiaokai-wang** [comment]
Great! 👍

**Comment by akatrevorjay** [comment]
I know, it caught me by surprise too.

Something to note: This module *must* be loaded *after* the streams module, provided both are loaded dynamically, or you run into `undefined reference` dyn linker errors.

**Pull request merged**
